art_pieces = {
    "The Virgin of the Rocks": {
        "image_file_path": "images/virgin of the rocks.jpg",
        "short_description":
            """
    Leonardo’s mysterious painting shows the Virgin Mary with Saint John the Baptist, Christ’s cousin, and an angel. All kneel to adore the infant Christ, who in turn raises his hand to bless them. They are crowded in a grotto overhung with rocks and dense with vegetation.

    The painting was part of a large, elaborate altarpiece made for the church of San Francesco Grande, Milan to celebrate the Immaculate Conception of the Virgin Mary. It replaced a similar picture Leonardo made earlier (now in the Louvre, Paris).

    Leonardo has used innovative painting techniques to give the impression that the figures are emerging from the darkness of this shaded setting. For example, he has blurred the edges of their forms to indicate the shadows that envelop them. The underdrawing (preliminary outlining of a composition) shows that he attempted a different design but later changed his mind so it is almost identical to the Louvre version.
            """,
        "long_description":
            """
            This is one of Leonardo’s most mysterious and complex pictures. It’s a rare survival of one of his large-scale painted works, and a key example of many of the techniques and innovations with which he transformed Italian painting. Leonardo began his painting career in Florence, but in the early 1480s he offered his services to Milan’s ruling family, the Sforzas. While in Milan, he received the commission to paint ‘The Virgin of the Rocks’.

The painting was to be part of a grand altarpiece which included a large sculpture of the Virgin Mary, probably placed above it. The chapel that the altarpiece was destined for was in the church of San Francesco Grande, a Franciscan convent in Milan. The chapel belonged to the newly-formed confraternity of the Immaculate Conception of the Virgin Mary and it was dedicated to this feast.

The notion of the Immaculate Conception, which emerged in the twelfth century, was highly controversial but championed by the Franciscans. The idea was important because in order for Christ to be born without original sin (which passed from Adam and Eve for disobeying God), his mother, Mary, also had to be free of sin. The doctrine’s supporters argued that the Virgin had been conceived by God even before the creation of the world – and so before original sin.

Leonardo’s painting was commissioned shortly after the pope officially sanctioned celebration of the feast in 1477. The subject was still so new that there was no standard way of showing it, giving Leonardo free rein to create a new composition. He painted the Virgin, an infant Saint John the Baptist – a gilded cross under his arm – and an angel, kneeling around Christ, a chubby cross-legged child. The three figures communicate with each other in silence while the angel acts as a heavenly witness to the scene. They are embedded in the landscape: foliage tickles Saint John’s knees and Christ’s toes, and rocks hem them in on all sides.

Writers who supported the Immaculate Conception defended their argument using biblical passages that expressed the pre-existence of divine Wisdom (later associated with the Virgin). One of these was a verse in which Wisdom says: ‘From the beginning and before the world, was I created, and unto the world to come I shall not cease to be’ (Ecclesiastes 24: 9). This might explain why Leonardo has placed the figures in a shady grotto, with views through the rocks to a watery landscape beyond. These primitive elements suggest the scene is set in the earliest moments of creation: the first verses of the biblical creation story tell of God creating the earth out of the watery deep. The rocks are shaped like rounded cones – they look as though they have just emerged from the depths of the earth, like volcanic eruptions. Their upward energy contrasts with the water’s stillness, the green of which suggests it is shallow, like a swamp. A haze over the water suggests its warmth – a fetid pool, ripe with the promise of life. The place is certainly fertile: the plants around Saint John the Baptist’s knees are firm and luscious, the leaves plump. Plants even sprout from the rocks above; the landscape is alive.

In this picture we see examples of many of Leonardo’s broad range of interests. His surviving drawings include numerous studies of nature: dramatic rock formations, trees and detailed plant studies. He was fascinated by the power of the natural world; he made nine drawings of an imaginary deluge, expressing the force of water. He paints the rocks of the holy grotto with immense attention to the detail of their texture; we can almost feel it ourselves under the infant Christ’s left hand. But the flowers don’t resemble any real flowers – they‘re hybrids of different plants.

Leonardo has used his inventive technique, now called aerial perspective, to give the impression of a vast landscape setting. He realised that we perceive the same colours differently depending on their distance from us; green appears blue if viewed from far off. By painting the mountains in the background blue, he tricks us into believing they are in the far distance. He softened their edges so they appear hazy, another technique that mimics the effects of vision in reality. The cool blue-green also contrasts directly with the rich, warm red-brown of the earth.

The figures emerge softly from the darkness of the grotto. Leonardo created this effect by painting very subtle, rather than stark, transitions between light and dark. This created a blurry effect around the edges of forms – look at the Virgin’s temples and nose for example – a technique later called sfumato. As with ’aerial perspective', this idea was a result of his experiments into vision and perception in this period. Leonardo built up his figures using layers of black and white underpainting, showing his knowledge of the way we perceive shapes through the effect of light and shadow on their surfaces.

Recent conservation work has revealed that Leonardo painted this, his second version of the picture, in three phases. He probably started in the early 1490s, painting the angel’s delicate gauze sleeve. Technical examination shows that a few years later he changed the position of Christ’s head, turning it from a three-quarter to profile view. In 1499 he left Milan for Florence to escape the turbulence caused by the French invasion of the city. He was summoned to return to finish the picture in 1506, when he added a layer of ultramarine (an expensive blue pigment) to the sky – as specifically mentioned in the original contract.

Our panel, begun about a decade after the first version, has been painted in a significantly different style. Some areas appear to be unfinished if viewed up close, but this was probably deliberate: it enables us to focus on the most important features. There are fewer colours too – it is mainly blue, yellow and brown. Leonardo has changed the angel’s robes from red to blue, probably to simplify the picture and focus attention on the Virgin’s yellow draperies.
            """
    },
    "An Old Woman ('The Ugly Duchess')": {
        "image_file_path": "images/the ugly duchess.jpeg",
        "short_description":
            """
        This must be one of the most arresting faces in the National Gallery’s Collection. An elderly woman with lively eyes set deep in their sockets, a snub nose, wide nostrils, pimply skin, a hairy mole, bulging forehead and a prominent square chin rests one hand on a marble parapet. Her neck is rumpled by age and she seems to have lost all her teeth. She is elegantly and aristocratically dressed, although by the time this picture was painted her clothes would have been many decades out of date and her cleavage considered scandalous. She brazenly challenges every traditional canon of beauty and rule of propriety.

        This painting is part of a pair: her ‘other half’ is in a private collection in New York. The old woman dons this flamboyant and provocative outfit in order to seduce the old man, to whom she offers a rosebud, a flower with sexual connotations. These are satirical portraits, mocking the vanity of the old who dress and behave as if they are still young. This painting captures the emergence of the grotesque (in the original sense of the word, denoting the surprising, unusual, and playful) as a subject for painting. Quinten Massys pioneered this type of secular, satirical imagery. A case of mistaken identity later earned her the nickname ‘The Ugly Duchess’.
        """,
        "long_description":
            """
            This must be one of the most arresting faces in the National Gallery’s Collection. An elderly woman with lively eyes set deep in their sockets, a snub nose, wide nostrils, pimply skin, a hairy mole, bulging forehead and a prominent square chin and rests one hand on a marble parapet. Her neck is rumpled by age and she seems to have lost all her teeth. She challenges every traditional canon of beauty. This striking work captures the emergence of the grotesque (in the original sense of the word, denoting the surprising, unusual, and playful) as a subject for painting. Quinten Massys pioneered this type of secular, satirical imagery.
    
    The woman’s clothes are rich. Defying the modesty expected from older women during the Renaissance, she is wearing a low-cut, uncovered, and tightly laced bodice that emphasises her wrinkly cleavage. Her hair is concealed in the horns of a heart-shaped bonnet, over which she has placed a white veil, secured by a large, bejewelled brooch. However fine her attire, by the time this panel was painted in the early sixteenth century her clothes would have been many decades out of date, prompting laughter rather than admiration. Her headdress had by then become an iconographic shorthand for female vanity, its horns compared to those of the devil.
    
    This painting is part of a pair: her ‘other half’, An Old Man also painted by Massys, is in a private collection in New York. The old woman dons this flamboyant and provocative outfit in order to seduce the old man, to whom she offers a rosebud, a flower with sexual connotations. She breaks conventions by appearing on the proper right, the more prestigious side reserved for men in double portraits. Viewers were invited to mock the foolishness of the old who behave as if they are still young.
    
    There has been speculation that the artist depicted a woman with Paget’s disease – a rare illness causing bone hypertrophy. Yet rather than painted from life, this figure was more probably a fictional, folkloric character from the world of carnival: the figure of the lavishly dressed old woman with a horned headdress recurs in several prints, miniatures, and misericords (the carved reliefs that adorned the underside of folding seats in choir stalls) of the period. In presenting such figures of fun as elaborate portraits, Massys parodied the dignified genre.
    
    Massys shared his interest in the expressive power of the human face with his contemporary, Leonardo da Vinci, who made countless studies of grotesque heads, many of which feature old women in similar attire. Two drawings of an old woman by followers of the artist show the same unforgettable face (Royal Library, Windsor Castle and New York Public Library). Massys probably took inspiration from Leonardo’s composition, as he did on other occasions. Yet he adeptly transformed the small drawing into an ambitious life-size painting, giving it a pendant and fleshing out its satirical content.
    
    Technical analysis confirms that the painting is an original, not a copy. infrared reflectograms have revealed a good deal of underdrawing. That for the face is carefully done, whereas that for the clothes and other elements is freer and sketchier. For the face, the artist may have carefully followed a preliminary drawing but made several changes. The eyes were drawn twice – they were moved slightly up and to the right – and the painted chin, neck and right ear are smaller than in the underdrawing. Her right shoulder was also redrawn in its present painted place and both hands are differently posed.
    
    Several idiosyncrasies of the painting technique support attribution to Massys himself. The paint is worked in many places wet-in-wet and has been dragged and feathered. In many places energetic feathering has been used to soften transitions of tone, a technique which seems to have been peculiarly Quinten’s. Some of the hair near the Duchess’ right ear and some of the embroidery on her right cuff are rendered in sgraffito, where the artist has scratched through a layer of still-wet paint to reveal what is underneath. The mottled areas of her flesh were achieved by spotting the basic pink with red and white dots, dashes and blotches. The skill of the brushwork is clear if you look very closely at the filigree of the brooch, where at least five shades of brown, orange, pink and yellow are found, and where a paint containing mainly lead-tin yellow is fairly heavily impastoed.
    
    The two horns of the headdress were rendered by different methods. On the right, the horn’s stripes have been made by removing the red, white and blue to reveal the black layer underneath; on the left, black paint has been applied on top. They may have been done by different assistants, or perhaps Massys discovered another way of executing the patterns which he preferred to the first.
    
    In the seventeenth century, the painting was misidentified as a portrait of Margaret Maultasch, Duchess of Carinthia and Countess of Tyrol, a historical figure who had been defamed by her enemies as the ‘ugliest woman in history’. On this basis, she later gained the nickname ‘The Ugly Duchess’. In the Victorian era, this picture (or one of its many versions) inspired John Tenniel’s depiction of the Duchess in his illustrations of Lewis Carroll’s Alice’s Adventures in Wonderland (1865). This entrenched the moniker and turned this figure into an icon for generations of readers.
            """
    },

    "Doge Leonardo Loredan": {
        "image_file_path": "images/doge.jpg",
        "short_description":
            """
            Leonardo Loredan knows that he is being looked at, but he does not return our gaze. He is the doge, the ruler of the Venetian Republic; elected in 1501, he ruled until his death in 1521.
            He wears white silk damask robes woven with gold and silver metal thread, clothing reserved for the most splendid occasions, including the feasts of Candlemas and the Annunciation. The armless, half-length representation recalls classical marble busts of emperors. Often placed on plinths – recalled here by the parapet – these were adopted in the Renaissance period for sculpted portraits of the powerful and wealthy.
            Bellini no doubt wanted to make this visual connection, but here he shows how he can surpass sculptural portraits through his mastery of oil paint. The subtle blending of colour in this slow-drying medium allowed him to create convincing tonal transitions when painting flesh. Oil paint also lends itself to slightly blurred contours; Loredan’s expression seems changeable, making him appear lifelike and immediate as well as distant and imposing.
            """,
        "long_description":
            """
Leonardo Loredan knows that he is being looked at, but he does not return our gaze. To do so would be to treat the viewer as an equal – but Loredan is the doge, the ruler of the Venetian Republic, and so no one looking at this picture could have been equal to him. He was elected in 1501 and ruled until his death in 1521.

Loredan appears to be scrutinising something. The intensity of his gaze, which suggests his intelligence, is reinforced by the pale blue of his small, deep-set eyes. This sternness is balanced by the enigmatic expression of his mouth: the slightly deeper crease in the wrinkle to the right of his lips suggests that he is about to break into a wry, one-sided smile – a smirk, maybe. This is counterbalanced again by the light around his left eye, which gives his expression an open sincerity. It’s as though Giovanni Bellini is showing all of the doge’s potential moods and dispositions, his capacity for severity and judgement as well as a sharp wit and openness to the truth.

Previously, portraits of Venice’s doges had traditionally followed the normal conventions for portraits of rulers, showing them in strict profile. Bellini has used the more contemporary three-quarter view, popularised in the city by artists like Antonello da Messina from the 1470s onwards, to explore Loredan’s character. His brother Gentile used it too, in his portrait of Doge Agostino Barbarigo (now in a private collection), but it was Giovanni who – in this portrait – fully developed its potential for realism as well as psychological expression.

As in portraits by van Eyck and Antonello, Bellini created the illusion that the sitter is lit by a strong light source coming from the left. It allowed him to give shape to the face, and to create the impression of three-dimensionality, by painting any protrusions that catch the glare in lighter shades and the flatter areas in shadow. The effect was enhanced by Bellini’s absolute mastery of painting in oil by this stage in his career. This slow-drying medium enabled him to blend colours together, avoiding harsh transitions and making changes in tone – particularly the flesh tones – appear natural. Subtle shading enabled him to describe the skin’s texture convincingly; the skin of Loredan’s neck is soft and loose and he has very fine wrinkles around his eyes – details that record his age, seen as a crucial component of wisdom.

Loredan is shown in the white robes he would have worn on the most splendid occasions, and the contrast of white and gold against the blue background makes him appear even more striking and dazzling. The gentle curve of the horned corno ducale (dogal cap) sweeps upwards gracefully. Several widths of expensive white silk damask fabric, woven with gold and silver metal thread, were sewn together to make the mantle. The pomegranate design came from eastern Mediterranean textiles and was popular in Renaissance fabrics. Loredan himself introduced white dogal robes for the processions celebrating the feasts of Candlemas and the Annunciation. If you look closely, you‘ll see that the design is upside down; the back – the view most people would see in ceremonial processions – showed the design upright. This kind of detail indicates that Bellini was observing and recording what he saw accurately, rather than imagining it: he probably borrowed the mantle so that he could take his time to paint it.

The blue background was painted using plenty of ultramarine – one of the most costly pigments available – mixed with white. It gives the sense that, while he is separated from us by the marble parapet, the space the doge occupies is infinite. This sense of openness makes it easier to imagine that if it weren’t for the parapet we might actually be able to walk around Loredan, as though he were a sculpture – an effect almost certainly sought by Bellini. The concealed arms and half-length representation recall classical marble busts of emperors; often placed on plinths, recalled here by the parapet, these were adopted during the Renaissance for sculpted portraits of the powerful and wealthy. The deep folds of the mantle and the shadow cast by the ornamental buttons (called campanoni d‘ori, ’golden bells‘) give the impression of a stiff, solid form resembling carved stone. But the short strokes of thick paint Bellini used to achieve a slightly rough texture where the light catches the gilt thread woven through the silk remind us that this isn’t a cold stone sculpture after all.

Rather than inscribe his name onto the picture, or paint it as though it was carved into the marble of the parapet, Bellini has made it look like a casual afterthought: his signature appears on a piece of paper that looks as though it has just been unfolded and stuck onto the marble. This is an astonishing act of false modesty, as it shows off Bellini’s skill at painting a range of materials, reinforcing their different textures by painting the one on top of the other.

The council room of the doge’s palace – the seat of government and the dogal residence – was decorated with a frieze of portraits of successive doges, recording their appearance for posterity. From 1474 Gentile Bellini was responsible for these portraits, which were destroyed by fire only one hundred years later. This picture was not part of that series – it was probably painted as a private commission. A poem by Lydio Catti, published in Venice in 1502, mentions Giovanni Bellini as Loredan’s portraitist and proves this was made before 1502.
"""
    },
    "Sunflowers": {
        "image_file_path": "images/sunflowers.png",
        "short_description":
            """
This is one of five versions of Sunflowers on display in museums and galleries across the world. Van Gogh made the paintings to decorate his house in Arles in readiness for a visit from his friend and fellow artist, Paul Gauguin.
‘The sunflower is mine’, Van Gogh once declared, and it is clear that the flower had various meanings for him. The different stages in the sunflower’s life cycle shown here, from young bud through to maturity and eventual decay, follow in the vanitas tradition of Dutch seventeenth-century flower paintings, which emphasise the transient nature of human actions. The sunflowers were perhaps also intended to be a symbol of friendship and a celebration of the beauty and vitality of nature.
The sunflower pictures were among the first paintings Van Gogh produced in Arles that show his signature expressive style. No other artist has been so closely associated with a specific flower, and these pictures are among Van Gogh’s most iconic and best-loved works.
            """,
        "long_description":
            """
‘The sunflower is mine’, Van Gogh once declared. Soon after his death he became known as the painter of sunflowers, an identification that endures to this day. No other artist has been so closely associated with a specific flower, and his sunflower pictures continue to be among Van Gogh’s most iconic – and loved – works.

This painting is one of five versions of Sunflowers on display in museums and galleries across the world, although Van Gogh painted seven versions in total between 1888 and 1889. Of the seven, one is in a private collection and has not been exhibited for generations. The other, bought by a Japanese collector in 1921, was destroyed during the Second World War. In addition to the National Gallery’s painting, the four other versions on public display are in the Van Gogh Museum in Amsterdam, the Neue Pinakothek in Munich, the Philadelphia Museum of Art and the Sompo Museum in Tokyo.

The seven pictures were made in two groups: four were painted in August 1888 and three replicas were painted in January 1889, which Van Gogh described as ‘absolutely equal and identical copies’. These copies, along with the original paintings, were to be used as side panels to versions of his portrait of Madame Roulin, the wife of the Arles postman. Van Gogh painted the first four versions of his sunflowers in just one week. He worked quickly before the flowers faded, writing to his brother Theo, ‘I am painting with the gusto of a Marseillaise eating bouillabaisse ... If I carry out this idea there will be a dozen panels. So the whole thing will be a symphony in blue and yellow.’ The first two paintings to be completed were the one now in a private collection and the painting destroyed by bombing. The second two paintings – Fourteen Sunflowers (Munich) and the National Gallery’s picture – are the most important of the series. Van Gogh considered both good enough to hang and signed them ‘Vincent’, using his first name only as people found it difficult to pronounce his last name. They were also among the few works he felt confident enough to exhibit in Brussels in November 1889.

Van Gogh had previously painted sunflower still lifes, but was prompted to paint this series by the imminent arrival of Paul Gauguin, his friend and fellow artist, at the ‘Yellow House’, his rented home in Arles. Van Gogh was anxious to please his guest, who arrived on 23 October, and he knew Gauguin liked his sunflower pictures. As he explained to Theo, ‘I would like to do a decoration for the studio. Nothing but large Sunflowers’ (although he changed his plans and hung two pictures – this one and the Munich painting – in the guest room which Gauguin was to use). Van Gogh hoped that Gauguin’s arrival would be the first step in forming a new ‘association’ of like-minded artists, a ‘Studio in the South’. However, following a fight on 23 December, when Van Gogh threatened Gauguin with a knife and then cut off part of his own left ear, Gauguin returned to Paris. Although the friends never saw each other again, they continued to write, and in one letter Gauguin asked Van Gogh to make a sunflower painting for him. While living with Van Gogh, Gauguin painted the portrait Van Gogh Painting Sunflowers (Van Gogh Museum, Amsterdam). The scene was imagined, as the sunflower season was over and Van Gogh did not work on his sunflower pictures at all during the two months Gauguin was in Arles.

Gauguin may have admired Van Gogh’s sunflowers – in 1887 he had exchanged one of his Martinique landscapes for two of Van Gogh’s small sunflower studies – and yellow may have been his favourite colour, but the flower also had significance for Van Gogh himself. In this painting the 15 sunflowers are in different stages of their life cycle, from young bud through to maturity and eventual decay and death. The bud in the lower left corner has yet to reach full flower, seven flowers are in full bloom and the other seven have lost their petals and are turning to seed. Van Gogh has brilliantly captured the textures of the flowers in these various stages. Long strokes follow the direction of the petals, leaves and stems, whose sinuous lines echo those of Art Nouveau; small raised dabs of stippled paint imitate the bristling seed heads. Here, especially, Van Gogh exploited the stiff consistency of the new oil paints introduced in the nineteenth century to create thick impasto effects.

The sunflowers’ life cycle follows the vanitas tradition of seventeenth-century Dutch flower painting, but the sunflower had also been associated with love, both sacred and profane, since the sixteenth century. This was because just as the sunflower turns to follow the sun, so the true believer follows Christ and the lover follows the object of their affection. This idea could be extended to other instances of devotion, such as the subject who follows a leader or to the notion of art following nature. For Van Gogh, the sunflower’s association with art and love may have included the idea of artistic friendship or partnership, which he hoped to forge with Gauguin. The sunflower may also have had even more personal meanings for him. In February 1890 he wrote to the critic Albert Aurier, suggesting that the two sunflower pictures he was exhibiting in Brussels (the Munich and London versions) might ‘express the idea symbolising "gratitude".’ Symbolism aside, sunflowers were also visually striking examples of the beauty and vitality of nature, with which Van Gogh had always had a strong bond.

The paintings were also important artistic statements, not least because they were among the first paintings Van Gogh produced in Arles that show his signature expressive style. In this painting Van Gogh limited his palette to just one primary colour – ‘a picture all in yellow’ as he described it – although yellow here ranges from rich orange ochre to the pale greenish yellow of the background. Yellow could signify happiness for Van Gogh, and it was also the colour of Provence and a tribute to the Provençal painter Monticelli who ‘depicted the south [of France] all in yellow, all in orange, all in sulphur’. Van Gogh, too, has created a similar effect of incandescent heat, particularly with the circular seed heads, which seem to stand in for the sun itself.
            """
    },
    "The Arnolfini Portrait": {
        "image_file_path": "images/couple.png",
        "short_description":
            """
This must be one of the most famous and intriguing paintings in the world. A richly dressed man and woman stand in a private room. They are probably Giovanni di Nicolao di Arnolfini, an Italian merchant working in Bruges, and his wife.

Although the room is totally plausible – as if Jan van Eyck had simply removed a wall – close examination reveals inconsistencies: there’s not enough space for the chandelier, and no sign of a fireplace. Moreover, every object has been carefully chosen to proclaim the couple’s wealth and social status without risking criticism for aping the aristocracy.

The man’s hand is raised, apparently in greeting. On the back wall, a large convex mirror reflects two men coming into the room, one of whom also raises his arm. Immediately above it is Van Eyck’s signature. Could the man in mirror be van Eyck himself, with his servant, coming on a visit?
            """,
        "long_description":
            """
This must be one of the most famous paintings in the world, and one of the most intriguing. A richly dressed man and woman stand in a private room. Although it looks as if Jan van Eyck painted a real room exactly has he saw it, every object has been carefully chosen to proclaim the couple’s wealth and social status without risking criticism for aping the aristocracy.

The house is of brick. Its window opens onto a garden, and a cherry tree can be glimpsed through the open shutters. The large and luxurious bed is covered with expensive red woollen cloth, and red cushions and fabric are scattered on the bedside chair and the bench. This is not a bedroom but a reception room, and the bed – the most expensive item of furniture in the house – is an essential part of its furnishings. The chair and bench are ornately carved, an oriental carpet lies on the floor and a splendid brass chandelier hangs from the ceiling. Even the carelessly scattered oranges indicate wealth; such fruit was extremely expensive. But this is not a palace: the floor is boarded and the walls are plastered rather than panelled or hung with tapestries. We are looking into a reception room in the comfortable, modern mansion of a wealthy merchant.

The room’s restrained luxury is equalled by the careful sartorial splendour of the couple. Their clothes are expensive and fashionable, but not flashy. The man wears a hat of plaited straw, and a dark tabard, probably of silk velvet, trimmed with brown fur. Under it is a black, possibly silk, doublet, with silver cuffs. His muddy pattens (overshoes) lie discarded on the floor. The woman wears a fine green wool overdress with elaborate dagged sleeves and a long train which falls in thick folds around her feet. It is trimmed with a white fur, possibly ermine or squirrel belly. She is not pregnant, though she might look it: she is holding up her bulky gown in front of her, as ladies commonly did. Her hair is caught up in fashionable but modest horns, held in red nets, and covered with an intricately folded veil.

So who are the people in this intimate setting? They are clearly husband and wife, and for many years the painting was understood as representing a marriage ceremony, though not anymore. From early on the painting was identified as showing one ‘Hernoul le Fin’ or ‘Arnoult Fin’. The Arnolfini were an extensive family of Italian merchants, with various members in Bruges at this period. The most likely candidate is Giovanni di Nicolao di Arnolfini, known as Giannino or Jehannin, who would have been in his late thirties in 1434. The lady is probably his second wife, whose identity is unknown. They may have been friends of van Eyck – he painted another portrait of the man at an older age (Staatliche Museen, Berlin). A large round mirror hangs right in the centre of the composition, its convex glass showing not just the compressed and contorted room but also two men coming in through a door behind us. The first man seems to be raising his left arm and stepping down steps from the passage. Immediately above the mirror is a flamboyant signature: Johannes de Eyck fuit hic. 1434 (‘Jan van Eyck was here. 1434’). Are the men in the mirror van Eyck himself and his servant, arriving on a visit?

Technical analysis tell us much about how the picture was made. Infrared reflectography shows that the underdrawing was done in stages. In the first one van Eyck sketched in the figures, the main pieces of furniture and the basic architecture of the room, but left out many of the objects for which the painting is now famous: the watchful terrier, the chandelier, the chair, the beads hanging on the wall and the discarded shoes. These were painted in at a late stage. Van Eyck also altered the man and woman’s faces and bodies. In the initial underdrawing, Arnolfini had a larger face and even odder features. His feet were in a different position, his robe was shorter and his hat larger. His wife originally looked up towards her husband and her features were lower, so her forehead seemed even higher. Van Eyck often manipulated his sitters‘ appearance to emphasise heads and hands, but here the faces, especially the man’s, have been altered substantially. Arnolfini must have been a strange-looking man, and in the second underdrawing van Eyck improved his proportions and idealised his features.

Even the room itself if not a literal record of the couple’s home. Although it looks as if van Eyck has simply removed a wall, close examination reveals inconsistencies. The chandelier cannot fit into the space it seems to occupy; there is no sign of a fireplace; the bed is too short and the ornate convex mirror on the back wall seems impossibly large. As usual, van Eyck created a perfectly convincing show of reality but altered things to fit his aesthetic purposes and perhaps also to accord with Arnolfini’s aspirations.

However, there is nothing unusual in the pigments used – this illusion of reality relied on van Eyck’s skill, not on any technical innovation. Look closely and you can see an astonishing level of detail. The oranges reflect in the polished wood of the casement, and the beads hanging by the bed cast both shadows and reflections on the wall behind. For a painting that seems so precise, it was surprisingly quickly and freely painted. Van Eyck was almost bouncing the paintbrush off the panel to get small touches of colour, and he used his fingers and the brush handles as well as the points of the brushes. We can see his thumbprint by the shadow of the dog’s leg, and the bristles of the brush hanging by the bed are scratched into the paint.

The painting has a fascinating afterlife. By the sixteenth century it was in the hands of Margaret of Austria, Regent of the Netherlands. From her, it migrated into the Spanish royal collection. It next appears in the possession of James Hay, a Scottish soldier who was in Spain during the Peninsular War (1807–14). We don’t know how Hay got it, but he brought it back to England and it was bought by the National Gallery in 1842 for ‘the moderate price’ of 600 Guineas. It was our first Netherlandish painting.
            """
    }
}
